export const GET_IVA_PERCENTAGES_LOADING = "GET_IVA_PERCENTAGES_LOADING";
export const GET_IVA_PERCENTAGES_SUCCESS = "GET_IVA_PERCENTAGES_SUCCESS";
export const GET_IVA_PERCENTAGES_FAILED = "GET_IVA_PERCENTAGES_FAILED";