export const CREATE_PRODUCT_DEFINITION_LOADING = "CREATE_PRODUCT_DEFINITION_LOADING";
export const CREATE_PRODUCT_DEFINITION_SUCCESS = "CREATE_PRODUCT_DEFINITION_SUCCES";
export const CREATE_PRODUCT_DEFINITION_FAILED = "CREATE_PRODUCT_DEFINITION_FAILED";

export const GET_PRODUCT_DEFINITIONS_LOADING = "GET_PRODUCT_DEFINITIONS_LOADING";
export const GET_PRODUCT_DEFINITIONS_SUCCESS = "GET_PRODUCT_DEFINITIONS_SUCCES";
export const GET_PRODUCT_DEFINITIONS_FAILED = "GET_PRODUCT_DEFINITIONS_FAILED";

export const DELETE_PRODUCT_DEFINITION_LOADING = "DELETE_PRODUCT_DEFINITION_LOADING";
export const DELETE_PRODUCT_DEFINITION_SUCCESS = "DELETE_PRODUCT_DEFINITION_SUCCES";
export const DELETE_PRODUCT_DEFINITION_FAILED = "DELETE_PRODUCT_DEFINITION_FAILED";

export const UPDATE_PRODUCT_DEFINITION_LOADING = "UPDATE_PRODUCT_DEFINITION_LOADING";
export const UPDATE_PRODUCT_DEFINITION_SUCCESS = "UPDATE_PRODUCT_DEFINITION_SUCCES";
export const UPDATE_PRODUCT_DEFINITION_FAILED = "UPDATE_PRODUCT_DEFINITION_FAILED";