export const CREATE_PRODUCT_TYPE_LOADING = "CREATE_PRODUCT_TYPE_LOADING";
export const CREATE_PRODUCT_TYPE_SUCCESS = "CREATE_PRODUCT_TYPE_SUCCES";
export const CREATE_PRODUCT_TYPE_FAILED = "CREATE_PRODUCT_TYPE_FAILED";

export const GET_PRODUCT_TYPES_LOADING = "GET_PRODUCT_TYPES_LOADING";
export const GET_PRODUCT_TYPES_SUCCESS = "GET_PRODUCT_TYPES_SUCCESS";
export const GET_PRODUCT_TYPES_FAILED = "GET_PRODUCT_TYPES_FAILED";

export const DELETE_PRODUCT_TYPE_LOADING = "DELETE_PRODUCT_TYPE_LOADING";
export const DELETE_PRODUCT_TYPE_SUCCESS = "DELETE_PRODUCT_TYPE_SUCCES";
export const DELETE_PRODUCT_TYPE_FAILED = "DELETE_PRODUCT_TYPE_FAILED";

export const UPDATE_PRODUCT_TYPE_LOADING = "UPDATE_PRODUCT_TYPE_LOADING";
export const UPDATE_PRODUCT_TYPE_SUCCESS = "UPDATE_PRODUCT_TYPE_SUCCES";
export const UPDATE_PRODUCT_TYPE_FAILED = "UPDATE_PRODUCT_TYPE_FAILED";