export const GET_PRODUCT_TYPES_LOADING = "GET_PRODUCT_TYPES_LOADING";
export const GET_PRODUCT_TYPES_SUCCESS = "GET_PRODUCT_TYPES_SUCCESS";
export const GET_PRODUCT_TYPES_FAILED = "GET_PRODUCT_TYPES_FAILED";