export const CREATE_EXPIRATION_DATE_LOADING = "CREATE_EXPIRATION_DATE_LOADING";
export const CREATE_EXPIRATION_DATE_SUCCESS = "CREATE_EXPIRATION_DATE_SUCCES";
export const CREATE_EXPIRATION_DATE_FAILED = "CREATE_EXPIRATION_DATE_FAILED";

export const GET_EXPIRATION_DATES_LOADING = "GET_EXPIRATION_DATES_LOADING";
export const GET_EXPIRATION_DATES_SUCCESS = "GET_EXPIRATION_DATES_SUCCES";
export const GET_EXPIRATION_DATES_FAILED = "GET_EXPIRATION_DATES_FAILED";

export const DELETE_EXPIRATION_DATE_LOADING = "DELETE_EXPIRATION_DATE_LOADING";
export const DELETE_EXPIRATION_DATE_SUCCESS = "DELETE_EXPIRATION_DATE_SUCCES";
export const DELETE_EXPIRATION_DATE_FAILED = "DELETE_EXPIRATION_DATE_FAILED";

export const UPDATE_EXPIRATION_DATE_LOADING = "UPDATE_EXPIRATION_DATE_LOADING";
export const UPDATE_EXPIRATION_DATE_SUCCESS = "UPDATE_EXPIRATION_DATE_SUCCES";
export const UPDATE_EXPIRATION_DATE_FAILED = "UPDATE_EXPIRATION_DATE_FAILED";