export const CREATE_EXPIRATION_DATE_LOADING = "CREATE_EXPIRATION_DATE_LOADING";
export const CREATE_EXPIRATION_DATE_SUCCESS = "CREATE_EXPIRATION_DATE_SUCCES";
export const CREATE_EXPIRATION_DATE_FAILED = "CREATE_EXPIRATION_DATE_FAILED";