export const CREATE_PRODUCT_TYPE_LOADING = "CREATE_PRODUCT_TYPE_LOADING";
export const CREATE_PRODUCT_TYPE_SUCCESS = "CREATE_PRODUCT_TYPE_SUCCES";
export const CREATE_PRODUCT_TYPE_FAILED = "CREATE_PRODUCT_TYPE_FAILED";

export const GET_PRODUCT_TYPES_LOADING = "GET_PRODUCT_TYPES_LOADING";
export const GET_PRODUCT_TYPES_SUCCESS = "GET_PRODUCT_TYPES_SUCCESS";
export const GET_PRODUCT_TYPES_FAILED = "GET_PRODUCT_TYPES_FAILED";

export const DETELE_PRODUCT_TYPE_LOADING = "DETELE_PRODUCT_TYPE_LOADING";
export const DETELE_PRODUCT_TYPE_SUCCESS = "DETELE_PRODUCT_TYPE_SUCCES";
export const DETELE_PRODUCT_TYPE_FAILED = "DETELE_PRODUCT_TYPE_FAILED";