export const CREATE_PRODUCT_TYPE_LOADING = "CREATE_PRODUCT_TYPE_LOADING";
export const CREATE_PRODUCT_TYPE_SUCCESS = "CREATE_PRODUCT_TYPE_SUCCES";
export const CREATE_PRODUCT_TYPE_FAILED = "CREATE_PRODUCT_TYPE_FAILED";