export const CREATE_PRODUCT_LOADING = "CREATE_PRODUCT_LOADING";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCES";
export const CREATE_PRODUCT_FAILED = "CREATE_PRODUCT_FAILED";

export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCES";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const DELETE_PRODUCT_LOADING = "DELETE_PRODUCT_LOADING";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCES";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const UPDATE_PRODUCT_LOADING = "UPDATE_PRODUCT_LOADING";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCES";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";