export const CREATE_PRODUCT_DEFINITION_LOADING = "CREATE_PRODUCT_DEFINITION_LOADING";
export const CREATE_PRODUCT_DEFINITION_SUCCESS = "CREATE_PRODUCT_DEFINITION_SUCCES";
export const CREATE_PRODUCT_DEFINITION_FAILED = "CREATE_PRODUCT_DEFINITION_FAILED";

export const GET_PRODUCT_DEFINITIONS_LOADING = "GET_PRODUCT_DEFINITIONS_LOADING";
export const GET_PRODUCT_DEFINITIONS_SUCCESS = "GET_PRODUCT_DEFINITIONS_SUCCES";
export const GET_PRODUCT_DEFINITIONS_FAILED = "GET_PRODUCT_DEFINITIONS_FAILED";